theme:
    name: readthedocs
    features:
        - navigation.sections  # Sections are included in the navigation on the left.
        - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.

site_name: cryojax
site_description: The documentation for cryojax.
site_author: Michael O'Brien
site_url: https://cryojax.github.io

repo_url: https://github.com/mjo22/cryojax
repo_name: mjo22/cryojax

plugins:
    - search  # default search plugin; needs manually re-enabling when using any other plugins
    - autorefs  # Cross-links to headings
    - mknotebooks  # Jupyter notebooks
    - mkdocstrings:
        handlers:
          python:
            setup_commands:
                - import jaxtyping
                - jaxtyping.set_array_name_format("array")
                - import jax
                - jax.ShapeDtypeStruct.__module__ = "jax"
                - jax.core.ClosedJaxpr.__module__ = "jax.core"
            selection:
            rendering:


nav:
    - 'index.md'
    - Simulator API:
        - Electron Density:
            - 'api/simulator/electron_density.md'