theme:
    name: material
    features:
        - navigation.sections  # Sections are included in the navigation on the left.
        - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.

site_name: cryojax
site_description: The documentation for cryojax.
site_author: Michael O'Brien
site_url: https://cryojax.github.io

repo_url: https://github.com/mjo22/cryojax
repo_name: mjo22/cryojax

plugins:
    - autorefs  # Cross-links to headings
    - mknotebooks  # Jupyter notebooks
    - mkdocstrings:
        handlers:
          python:
            paths: [src]  # search packages in the src folder
            options:
              annotations_path: full
              inherited_members: true
              show_root_heading: true
              show_root_full_path: true
              show_if_no_docstring: true
              show_signature_annotations: true
              signature_crossrefs: true
              show_source: false
              members_order: source
              heading_level: 12
        


nav:
    - 'index.md'
    - Simulator API:
        - Electron Density:
            - 'api/simulator/electron_density.md'