name: Build docs

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        python-version: [ "3.10" ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mkdocs
          pip install mkdocs-gen-files
          pip install mkdocs-same-dir
          pip install pymdown-extensions
          pip install mkdocs-pymdownx-material-extras
          pip install mkdocs-autorefs  
          pip install mkdocs-simple-plugin
          pip install mkdocstrings-python
          pip install mkdocs-material

      - name: Deploy documentation
        run: mkdocs gh-deploy
